[package]
name = "scheduling_interview"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
csv = "1.3.0"
mockall = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"